### ISSUE TITLE
Small log issue when converting+deleting screenshots

### ISSUE THREAD

**Issue by SabreML** [EDDiscovery/EliteDangerousCore#115]
If the screenshot conversion settings are set to delete the original `.bmp` file after converting it, the program log entry for the conversion will have an empty space where the deleted file name should be:

![Capture](https://user-images.githubusercontent.com/57483089/211123482-0bbab9d9-f9e8-41b6-a2cd-aaa19f419b28.PNG)
*(This should instead be 'Converted `X` to `Y`')*
<hr>

Based on a quick look at the code, the problem seems to be line 248 at the end of the `Convert()` method here:
https://github.com/EDDiscovery/EliteDangerousCore/blob/87f42036cb47fb5e0d86add01dd75a2f553fd3ec/EliteDangerous/Screenshots/ScreenShotImageConverter.cs#L246-L250
`Path.GetFileName(inputfilename)` is returning `null`, presumably because the file at `inputfilename`'s location has been deleted, so the log entry gets an empty space added to it rather than a file path.

This seems like an easy "bug" to fix, but I don't know anything about the codebase so I figured I'd post an issue about it rather than messing something up myself.

**Comment by robbyxp1** [comment]
Thank you - finally fixed it. In devEDSM.
