### ISSUE TITLE
Engineering info is missing for 5 engineers

### ISSUE THREAD

**Issue by Sannemen** [EDDiscovery/EliteDangerousCore#6]
Engineering info is missing for 5 different engineers:

- Chloe Sedesi
- Etienne Dorn
- Mel Brandon
- Marsha Hicks
- Petra Olmanova

I've looked at their definitions, but they explicitly mention this to be automatically generated by a "netlogentry frontierdata scanner", although I was not able to find any reference to it. Any guidance on this, that I can use to submit a PR?

**Comment by robbyxp1** [comment]
Thanks for this info. I've updated the table.
